homework20/src/main/java/com/epam/training/saladkou/hw20/entity/Order.java
package com.epam.training.saladkou.hw20.entity;

import java.util.HashMap;
import java.util.Map;

public class Order {

    public Order(int id) {
        this.id = id;
        items = new HashMap<>();
    }

    public Order() {
        this(0);
    }

    public int getId() {
        return id;
    }

    public Map<Good, Integer> getItems() {
        return items;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setItems(Map<Good, Integer> items) {
        this.items = items;
    }

    public boolean addItem(Good good, int amount) {
        items.put(good, amount);
        return true;
    }

    public boolean addItem(Good item) {
        Good good = getProductFromOrderById(item.getId());
        if (good == null) {
            items.put(item, 1);
        } else {
            int amount = items.get(good);
            items.put(good, ++amount);
        }
        return good == null;
    }

    private Good getProductFromOrderById(Integer goodId) {
        for (Good good : items.keySet()) {
            if (good.getId() == goodId) {
                return good;
            }
        }
        return null;
    }


    private Map<Good, Integer> items;
    private int id;


    public double getTotalSum() {
        double sum = 0;
        for (Good good : items.keySet()) {
            int amount = items.get(good);
            sum += good.getPrice() * amount;
        }
        return sum;
    }

    @Override
    public String toString() {
        return "Order{"
                + "id=" + id
                + "items=" + items + '}';
    }
}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/AuthController.java
package com.epam.training.saladkou.hw20.controllers;


import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/auth")
public class AuthController {

    private static final String AUTH_PAGE = "auth";

    @GetMapping
    public String authShowForm() {
        return AUTH_PAGE;
    }


}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/CartController.java
package com.epam.training.saladkou.hw20.controllers;

import com.epam.training.saladkou.hw20.requesthandlers.CartPageRequestHandler;
import org.apache.log4j.Logger;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.HttpSession;

@Controller
@RequestMapping("/cart")
public class CartController {


    private static final String REFERER_PARAM = "referer";
    private static final String LOGIN_PARAM = "login";
    private static final String ORDERED_ITEM_PARAM = "orderedItem";
    private static final String ACTION_PARAM = "act";
    private static final String CART_PAGE = "cart";
    private static final String AUTH_PAGE = "auth";


    public CartController(CartPageRequestHandler requestHandler) {
        this.requestHandler = requestHandler;
    }

    private final CartPageRequestHandler requestHandler;


    private final Logger logger = Logger.getLogger(CartController.class);


    @PostMapping
    public String cart(@RequestHeader(REFERER_PARAM) String referer,
                       @RequestParam(value = LOGIN_PARAM, required = false) String login,
                       @RequestParam(value = ORDERED_ITEM_PARAM, required = false) Integer goodId,
                       @RequestParam(value = ACTION_PARAM, required = false) String action,
                       HttpSession session, Model model) {

        logger.info("referer header: " + referer);

        String viewName = CART_PAGE;

        if (referer.endsWith(AUTH_PAGE)) {
            viewName = requestHandler.handleRequestFromAuthPage(login, session, model);
        }

        if (referer.endsWith(CART_PAGE)) {
            viewName = requestHandler.handleRequestFromCartPage(action, goodId, session, model);
        }
        return viewName;
    }

}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/ErrorController.java
package com.epam.training.saladkou.hw20.controllers;


import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping("/error")
public class ErrorController {

    private static final String ERROR_PAGE = "error";

    @GetMapping
    public String accessError() {
        return ERROR_PAGE;
    }
}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/HistoryController.java
package com.epam.training.saladkou.hw20.controllers;

import com.epam.training.saladkou.hw20.entity.Order;
import com.epam.training.saladkou.hw20.entity.User;
import com.epam.training.saladkou.hw20.repository.OrderRepository;
import org.apache.log4j.Logger;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.List;
import java.util.Optional;
import javax.servlet.http.HttpSession;


@Controller
@RequestMapping("/history")
public class HistoryController {

    private static final String USER_ATTRIBUTE = "user";
    private static final String HISTORY_ATTRIBUTE = "history";
    private static final String HISTORY_PAGE = "history";


    public HistoryController(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }

    OrderRepository orderRepository;

    private final Logger logger = Logger.getLogger(HistoryController.class);

    @GetMapping
    public String history(HttpSession session, Model model) {
        User user = (User) session.getAttribute(USER_ATTRIBUTE);
        Optional<List<Order>> historyOptional = orderRepository.getOrdersByUserId(user.getId());
        historyOptional.ifPresent(history -> model.addAttribute(HISTORY_ATTRIBUTE, history));
        if (historyOptional.isPresent()) {
            model.addAttribute(HISTORY_ATTRIBUTE, historyOptional.get());
        } else {
            logger.warn("Order history is empty");
        }
        return HISTORY_PAGE;
    }

}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/HomeController.java
package com.epam.training.saladkou.hw20.controllers;

import com.epam.training.saladkou.hw20.repository.OrderRepository;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
@RequestMapping(value = {"/", "/home"})
public class HomeController {

    private static final String HOME_PAGE = "home";

    public HomeController(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }

    OrderRepository orderRepository;

    @GetMapping()
    public String home() {
        return HOME_PAGE;
    }


}

homework20/src/main/java/com/epam/training/saladkou/hw20/controllers/OrderController.java
package com.epam.training.saladkou.hw20.controllers;

import com.epam.training.saladkou.hw20.entity.Order;
import com.epam.training.saladkou.hw20.entity.User;
import com.epam.training.saladkou.hw20.repository.OrderRepository;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpSession;

@Controller
@RequestMapping("/order")
public class OrderController {


    private static final String ORDER_ATTRIBUTE = "order";
    private static final String ORDER_PAGE = "order";
    private static final String USER_ATTRIBUTE = "user";

    public OrderController(OrderRepository orderRepository) {
        this.orderRepository = orderRepository;
    }

    private final OrderRepository orderRepository;

    @GetMapping
    public String order(HttpSession session, Model model) {

        Order order = (Order) session.getAttribute(ORDER_ATTRIBUTE);
        User user = (User) session.getAttribute(USER_ATTRIBUTE);

        orderRepository.addOrderToUser(order, user.getId());
        model.addAttribute(USER_ATTRIBUTE, user);
        model.addAttribute(ORDER_ATTRIBUTE, order);

        return ORDER_PAGE;
    }
}

homework20/src/main/webapp/WEB-INF/views/auth.jsp
    <html>
        <head>
        <title>Authorization page</title>
        </head>
        <body>
        <form  method="post" action="cart" >
        <input type="text" placeholder="Enter your name" name = "login">
        <br>
        <input type="checkbox" name = "access">
        <label>I agree with the terms of service</label>
        <br><br>
        <input type="submit" value="Enter">
        </form>
        </body>
        </html>

homework20/src/main/webapp/WEB-INF/views/cart.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html>
<head>
    <title>Cart page</title>
</head>
<body>
<p>Hello ${user.login} !</p>


<p>You have already ordered</p>

<c:forEach items="${order.items.keySet()}" var="good">
    <c:set var="amount" value="${order.items.get(good)}"/>
    ${good.title} x${amount}<br>
</c:forEach>

<form name="orderForm" method="post" action="cart">
    <p>Make your order <br></p>
    <select name="orderedItem">
        <c:forEach var="good" items="${goods}">
            <option value="${good.id}">${good}</option>
        </c:forEach>
    </select><br><br>
    <input name="act" type="submit" value="Add Item">
    <input name="act" type="submit" value="Submit">
</form>

<br><a href="history">Your order history</a>

</body>
</html>

homework20/src/main/webapp/WEB-INF/views/error.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Error page</title>
</head>
<body>
<h1>Oops!</h1>
<p>You shouldn't be here</p>
<p>Please, agree with the terms of service first</p>
<br>
<a href=home>Start page</a>
</body>
</html>

homework20/src/main/webapp/WEB-INF/views/history.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="с" uri="http://java.sun.com/jsp/jstl/core" %>

<html>
<head>
    <title>Order history</title>
</head>
<body>
<h3>Here is your order history</h3>


<с:forEach items="${history}" var="order">


    <table border="1">
        <caption>Order № ${order.id}</caption>
        <tr>
            <td>Good</td>
            <td>Price</td>
            <td>Amount</td>
            <td>Sum</td>
        </tr>


        <c:forEach items="${order.items.keySet()}" var="good">
            <c:set var="amount" value="${order.items.get(good)}"/>

            <tr>
                <td>${good.title}</td>
                <td>${good.price}</td>
                <td>${amount}</td>
                <td>${good.price*amount}</td>
            </tr>

        </c:forEach>
        <tr>
            <td>Total price</td>
            <td></td>
            <td></td>
            <td>${order.totalSum}</td>
        </tr>
        <br></table>
</с:forEach>

</body>
</html>

homework20/src/main/webapp/WEB-INF/views/home.jsp
<html>
<head>
    <title>Online shop</title>
</head>
<body>
<h3>Welcome to Online shop</h3>
<a href="auth">Sign in</a>
</body>
</html>

homework20/src/main/webapp/WEB-INF/views/order.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Order page</title>
</head>
<body>

<p>Dear, ${user.login} your order is</p>

<c:forEach items="${order.items.keySet()}" var="good">
    <c:set var="amount" value="${order.items.get(good)}"/>
    ${good.title} x${amount}<br>
</c:forEach>
<p>Total: ${order.totalSum}</p>
</body>
</html>